#:kivy 2.2.1

<NormalMenuPageWidget>:
  BoxLayout:
    id: layout
    pos: self.pos
    size: self.size
    orientation: 'vertical'
    spacing: dp(7)

    ItemWidget:
      item: root.items[0] if len(root.items) > 0 else None
      size_hint: 1, None

    ItemWidget:
      item: root.items[1] if len(root.items) > 1 else None
      size_hint: 1, None

    ItemWidget:
      item: root.items[2] if len(root.items) > 2 else None
      size_hint: 1, None
